name: release

permissions:
    contents: write

on:
    push:
    pull_request:

env:
    GITHUB_TOKEN: ${{ github.token }}
    RUST_BACKTRACE: 1

jobs:
    release:
        name: Release - ${{ matrix.platform.os-name }}
        strategy:
            fail-fast: false
            matrix:
                # https://github.com/actions/runner-images
                # riscvランナーが一生待機中なので、riscvをサポートする日は訪れません
                # https://github.com/apps/rise-risc-v-runners-personal
                platform:
                    - os-name: Linux-x86_64
                      runs-on: ubuntu-24.04
                      target: x86_64-unknown-linux-musl
                      use-cross: true
                    - os-name: Linux-aarch64
                      runs-on: ubuntu-24.04
                      target: aarch64-unknown-linux-musl
                      use-cross: true
                    - os-name: Linux-riscv64
                      runs-on: ubuntu-24.04-riscv
                      target: riscv64gc-unknown-linux-musl
                      use-cross: false

                    - os-name: Windows-x86_64
                      runs-on: windows-2025
                      target: x86_64-pc-windows-msvc
                      use-cross: true
                    - os-name: Windows-aarch64
                      runs-on: windows-11-arm
                      target: aarch64-pc-windows-msvc
                      use-cross: true

                    - os-name: macOS-aarch64
                      runs-on: macos-26
                      target: aarch64-apple-darwin
                      use-cross: true
        runs-on: ${{ matrix.platform.runs-on }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: ${{ matrix.platform.target }}
                  override: true
                  profile: minimal
            - uses: Swatinem/rust-cache@v2
              with:
                  key: ${{ matrix.platform.runs-on }}-${{ matrix.platform.target }}
            - name: Install cargo-post (macOS only)
              if: "matrix.platform.target == 'aarch64-apple-darwin'"
              run: cargo install cargo-post

            - name: Build Sender & Receiver with Cargo post-build (macOS only)
              if: "matrix.platform.target == 'aarch64-apple-darwin'"
              run: |
                  cargo post build --package open_remote_url_sender --locked --release --target ${{ matrix.platform.target }}
                  cargo post build --package open_remote_url_receiver --locked --release --target ${{ matrix.platform.target }}

            - name: Build Sender & Receiver with Cargo or Cross (non-macOS)
              if: "matrix.platform.target != 'aarch64-apple-darwin' && matrix.platform.target != 'riscv64gc-unknown-linux-musl'"
              uses: actions-rs/cargo@v1
              with:
                  use-cross: ${{ matrix.platform.use-cross }}
                  command: build
                  args: --manifest-path Cargo.toml --locked --release --target ${{ matrix.platform.target }}

            - name: Install RISCV host-tools
              if: matrix.platform.target == 'riscv64gc-unknown-linux-musl'
              shell: bash
              run: |
                  git clone https://github.com/sophgo/host-tools --depth=1
                  echo "$(pwd)/host-tools/gcc/riscv64-linux-musl-x86_64/bin" >> $GITHUB_PATH

            - name: Build Sender & Receiver RISCV with Cargo or Cross
              if: matrix.platform.target == 'riscv64gc-unknown-linux-musl'
              uses: actions-rs/cargo@v1
              env:
                  RUSTFLAGS: "-Ctarget-feature=+crt-static"
              with:
                  use-cross: ${{ matrix.platform.use-cross }}
                  command: build
                  args: --manifest-path Cargo.toml --locked --release --target ${{ matrix.platform.target }}

            - name: Determine Extra Files
              shell: bash
              run: |
                  if [[ "${{ matrix.platform.target }}" == *"-apple-darwin" ]]; then
                    echo "EXTRA_FILES<<EOF" >> $GITHUB_ENV
                    echo "OpenRemoteURLSender.app.zip" >> $GITHUB_ENV
                    echo "sender/inactive.env" >> $GITHUB_ENV
                    echo "README.md" >> $GITHUB_ENV
                    echo "README.ja_JP.md" >> $GITHUB_ENV
                    echo "README.ja_EZ.md" >> $GITHUB_ENV
                    echo "README.zh_CN.md" >> $GITHUB_ENV
                    echo "EOF" >> $GITHUB_ENV

                    echo "RECEIVER_EXTRA_FILES<<EOF" >> $GITHUB_ENV
                    echo "OpenRemoteURLReceiver.app.zip" >> $GITHUB_ENV
                    echo "receiver/inactive.env" >> $GITHUB_ENV
                    echo "README.md" >> $GITHUB_ENV
                    echo "README.ja_JP.md" >> $GITHUB_ENV
                    echo "README.ja_EZ.md" >> $GITHUB_ENV
                    echo "README.zh_CN.md" >> $GITHUB_ENV
                    echo "EOF" >> $GITHUB_ENV
                  elif [[ "${{ matrix.platform.target }}" == *"-pc-windows-"* ]]; then
                    echo "EXTRA_FILES<<EOF" >> $GITHUB_ENV
                    echo "sender/inactive.env" >> $GITHUB_ENV
                    echo "README.md" >> $GITHUB_ENV
                    echo "README.ja_JP.md" >> $GITHUB_ENV
                    echo "README.ja_EZ.md" >> $GITHUB_ENV
                    echo "README.zh_CN.md" >> $GITHUB_ENV
                    echo "EOF" >> $GITHUB_ENV

                    echo "RECEIVER_EXTRA_FILES<<EOF" >> $GITHUB_ENV
                    echo "receiver/inactive.env" >> $GITHUB_ENV
                    echo "README.md" >> $GITHUB_ENV
                    echo "README.ja_JP.md" >> $GITHUB_ENV
                    echo "README.ja_EZ.md" >> $GITHUB_ENV
                    echo "README.zh_CN.md" >> $GITHUB_ENV
                    echo "EOF" >> $GITHUB_ENV
                  else
                    echo "EXTRA_FILES<<EOF" >> $GITHUB_ENV
                    echo "scripts/install/install.sh" >> $GITHUB_ENV
                    echo "scripts/uninstall/uninstall.sh" >> $GITHUB_ENV
                    echo "scripts/config/config.sh" >> $GITHUB_ENV
                    echo "sender/inactive.env" >> $GITHUB_ENV
                    echo "README.md" >> $GITHUB_ENV
                    echo "README.ja_JP.md" >> $GITHUB_ENV
                    echo "README.ja_EZ.md" >> $GITHUB_ENV
                    echo "README.zh_CN.md" >> $GITHUB_ENV
                    echo "EOF" >> $GITHUB_ENV

                    echo "RECEIVER_EXTRA_FILES<<EOF" >> $GITHUB_ENV
                    echo "scripts/install/install.sh" >> $GITHUB_ENV
                    echo "scripts/uninstall/uninstall.sh" >> $GITHUB_ENV
                    echo "scripts/config/config.sh" >> $GITHUB_ENV
                    echo "receiver/inactive.env" >> $GITHUB_ENV
                    echo "README.md" >> $GITHUB_ENV
                    echo "README.ja_JP.md" >> $GITHUB_ENV
                    echo "README.ja_EZ.md" >> $GITHUB_ENV
                    echo "README.zh_CN.md" >> $GITHUB_ENV
                    echo "EOF" >> $GITHUB_ENV
                  fi

            - name: Wait
              shell: bash
              run: sleep $((RANDOM % 20 + 3))
            - name: Release Sender 1
              id: release-sender-1
              uses: houseabsolute/actions-rust-release@v0
              env:
                  CRATE_NAME: open_remote_url-sender
              with:
                  working-directory: .
                  executable-name: open-remote-url-sender
                  target: ${{ matrix.platform.target }}
                  extra-files: ${{ env.EXTRA_FILES }}
                  _force-release-for-testing: true
                  action-gh-release-parameters: |
                      {
                          "repository": "NaeCqde/open_remote_url",
                          "token": "${{ secrets.GITHUB_TOKEN }}"
                      }
            - name: Wait
              if: failure()
              shell: bash
              run: sleep $((RANDOM % 20 + 5))
            - name: Release Sender 2
              if: failure()
              id: release-sender-2
              uses: houseabsolute/actions-rust-release@v0
              env:
                  CRATE_NAME: open_remote_url-sender
              with:
                  working-directory: .
                  executable-name: open-remote-url-sender
                  target: ${{ matrix.platform.target }}
                  extra-files: ${{ env.EXTRA_FILES }}
                  _force-release-for-testing: true
                  action-gh-release-parameters: |
                      {
                          "repository": "NaeCqde/open_remote_url",
                          "token": "${{ secrets.GITHUB_TOKEN }}"
                      }

            - name: Wait
              shell: bash
              run: sleep $((RANDOM % 20 + 3))
            - name: Release Receiver 1
              id: release-receiver-1
              uses: houseabsolute/actions-rust-release@v0
              env:
                  CRATE_NAME: open_remote_url_receiver
              with:
                  working-directory: .
                  executable-name: open-remote-url-receiver
                  target: ${{ matrix.platform.target }}
                  extra-files: ${{ env.RECEIVER_EXTRA_FILES }}
                  _force-release-for-testing: true
                  action-gh-release-parameters: |
                      {
                          "repository": "NaeCqde/open_remote_url",
                          "token": "${{ secrets.GITHUB_TOKEN }}"
                      }
            - name: Wait
              if: failure()
              shell: bash
              run: sleep $((RANDOM % 20 + 5))
            - name: Release Receiver 2
              if: failure()
              id: release-receiver-2
              uses: houseabsolute/actions-rust-release@v0
              env:
                  CRATE_NAME: open_remote_url_receiver
              with:
                  working-directory: .
                  executable-name: open-remote-url-receiver
                  target: ${{ matrix.platform.target }}
                  extra-files: ${{ env.RECEIVER_EXTRA_FILES }}
                  _force-release-for-testing: true
                  action-gh-release-parameters: |
                      {
                          "repository": "NaeCqde/open_remote_url",
                          "token": "${{ secrets.GITHUB_TOKEN }}"
                      }
